### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [milostosic/rmem#2]
I would like to point out that an identifier like “[`__RMEM_HOOK_H__`](https://github.com/milostosic/rmem/blob/517a174811b7199145ce3854cfed7bbeb177e80e/src/rmem_hook.h#L6 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by milostosic** [comment]
Cleaned up.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/milostosic/rmem/commit/7bef0be086d264f71ba7cd01bd86fa83be1c57d4 "Fix header guards").
