### ISSUE TITLE
RMEM_STACK_TRACE_ENABLE_HASHING is not thread-safe

### ISSUE THREAD

**Issue by wickerwaka** [milostosic/rmem#3]
The callstack hashing system is not thread-safe. The caching structures themselves are not strictly thread-safe, but I don't think it is an issue in practice. There is the possible race condition when adding a new entry and you could end up with some mismatched entries in the cache. But I think the most common outcome is that the cache is less efficient because you could get some garbage entries in there is two threads wrote into the same stackIndex at the exact same time. 

The problem I have encountered is the order the stacktraces are written to the data stream is not guaranteed.

Thread A encounters new callstack and records it in the cache
Context switch occurs and Thread B becomes active
Thread B encounters the same callstack and finds it in the cache
Thread B, having found the callstack cached, just writes the hash to the output stream.
Context switch occers and Thread A becomes active
Thread A writes the full callstack to the output stream.

The MTuner tool will error during reading when it encounters the hash written by Thread B because it hasn't encountered the full stack from Thread A first.

My local workaround for this is to write a placeholder value into (`0xffffffff`) into `m_stackTraceHashes` when adding a new entry and then replace it with the correct hash value after I have written to the output stream.

**Comment by milostosic** [comment]
Thanks! Yes, the scenario you describe is indeed possible :/
I'd be interested to see the modification you did - if you don't mind you could create a pull request or simply send me the diff to check it out.

**Comment by wickerwaka** [comment]
Here you go: https://github.com/milostosic/rmem/pull/4

**Comment by milostosic** [comment]
Cheers!
