### ISSUE TITLE
Stack corruption in MemoryHook::alloc

### ISSUE THREAD

**Issue by zach-brockway** [milostosic/rmem#5]
Duplicated from [here](https://github.com/milostosic/rmem/commit/f64b6c53dda9358a0baaa8c11127286d377b585e#r38421484) because I realized I should file an issue:

I'm getting the following runtime check exception in debug builds of my app, when `MemoryHook::alloc` is called:

>Run-Time Check Failure #2 - Stack around the variable 'tmpBufferPtr' was corrupted.

It looks like `addStackTrace_new` still tries to write `sizeof(uintptr_t)*_numFrames` to a stack allocated buffer that's now only the fixed 96 bytes.

**Comment by milostosic** [comment]
Ooops. you're right. Fixed now. Thanks!
