### ISSUE TITLE
Support for building with clang-cl on windows

### ISSUE THREAD

**Issue by ompadu** [milostosic/rmem#6]
Hi 

I'm working on building rmem as part of a CMake project compiled with clang-cl on Windows, but `error: "Unsupported compiler!"` lights up at `rmem_platform.h:132`

Any chance this build configuration (clang-cl/Windows) will be supported?

**Comment by milostosic** [comment]
It's fixed, it was just a missing macro...

**Comment by ompadu** [comment]
Thank you!
