### ISSUE TITLE
using RMEM_TAG in multiple dlls requires shared `rmem::MemoryHook` 

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [milostosic/rmem#7]
I've started using MTuner and rmem to profile heap allocations, and I've been enjoying it very much so far.

I have a big project setup with each dll doing specialized work and I cannot seem to find a good way to make MTuner tagging functionality to work within different modules/dlls. 

By reading some code I've figured out that the `getMemoryHookPtr()` function in rmem_lib.cpp creates a separate MemoryHook instance for each module because of the static local variable.
```c++
rmem::MemoryHook*& getMemoryHookPtr()
{
	static rmem::MemoryHook* ptr = NULL;
	return ptr;
}
```

The only thing important to me is being able to RMEM_TAG several places existing in different dlls.

From the `rmem_sample_linker` example I see that I should call `rmemHookAllocs(1, 0);` the very first thing when entering the `.exe` main function.
`rmemHookAllocs` eventually calls `rmemInit` and initializes the local (to dll) copy of the MemoryHook.

The problem is ONLY the main `.exe` hook is used for the mtuner results apparently. so other dlls and modules should somehow have access to a shared `MemoryHook` object.

The only solution I found currently is include expose(export) the `rmem::MemoryHook*& getMemoryHookPtr()` function in `rmem.h` and forward declare `rmem::MemoryHook` like this:
```
namespace rmem { class MemoryHook; }
```
then I can pass share this pointer between different dlls.

I'm not an expert in writing a memory profiler but I think this is the fastest solution; and any solution requires either sharing the MemoryHook pointer or any other object that represents the main state of rmem (which imo shouldn't be a static var).

Please let me know if there is some other solution to handling multi-dll projects that I'm missing.

For what it's worth I'm on windows and I've built using `genie vs2022`

**Comment by milostosic** [comment]
Hi Erfan, You're correct that multiple DLLs are not going to work properly without extra work, this goes for all functionality including tags. MTuner was written with static linking in mind and rmem needs some extra work to make dynamic linking possible - I'll look into adding this feature properly but cannot commit to a specific time.

**Comment by Erfan-Ahmadi** [comment]
That's alright, you might want to take a look at wolfpd/tracy where it specifically has guides in it's documentation about multi dll setups.

**Comment by milostosic** [comment]
I'm trying to understand your setup here.. how is your project structured? Since you are using tags it seems like you're linking all those DLLs to rmem static library? If that's the case then yes - there's no way for this to work and you'd need to wrap the library in a DLL, similar to what's described in the documentation of tracy. rmem, as is - works for statically linked projects and is injected via DLL on Windows from MTuner GUI.

The rationale behind using a static buffer/variable is that rmem performs no allocations avoiding to pollute the heap and the need to handle callbacks for internal allocations.

**Comment by Erfan-Ahmadi** [comment]
Theoretically this setup should work, by creating a special Profiling dll project that statically links to rmem and other projects link to that project dynamically. This way there is only a single instance of the hook's static variable in it's translation unit.
Now after using Tracy for a while. I believe a similar setup should work for rmem. And I was wrong to statically link against rmem individually at the first place. (I have no idea why I didn't try this).

So I guess a simple warning in rmem documentation for multiple dll projects would suffice so that people don't make these kind of stupid mistakes like me. 

Even without the tags I think it's best practice to wrap rmem around special dll in multidll project. It may help with the hooking by initializing before other dlls are loaded.

**Comment by milostosic** [comment]
It's already wrapped when being injected via MTuner, rmem alone does what its purpose is so I'll be closing this.
